general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:

    parallels:
      priority_level_1: [pl_floor_intake, pl_prime, pl_shoot, pl_protect]

    ss_drivetrain:
      priority_level_2: []
      priority_level_1: []
      default: [st_drivetrain]

    ss_collector:
      priority_level_2: [st_collector_zero]
      priority_level_1: [st_collector_floor_intake, st_collector_retract]
      default: [st_collector_extend]

    ss_hopper:
      priority_level_2: [st_hopper_zero]
      priority_level_1: [st_hopper_home, st_hopper_collect, st_hopper_shoot]
      default: [st_hopper_stop]

  subsystems: [ss_drivetrain, ss_collector, ss_hopper]

  input_booleans: [
    ipb_driver_left_trigger, ipb_operator_left_bumper, ipb_operator_left_trigger, ipb_operator_right_trigger, ipb_operator_right_bumper
  ]

  input_numerics: [
    ipn_driver_left_y, ipn_driver_right_x,
  ]

  input_vectors: []

  output_numerics: [opn_drivetrain_left, opn_drivetrain_right, opn_collector_rollers]

  output_booleans: [opb_drivetrain_gear_shifter, opb_collector_solenoid]


global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_drivetrain:
  x: ipn_driver_right_x
  y: ipn_driver_left_y
  gear_shift: ipb_driver_left_trigger

# global_collector:

log:

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values: